### ISSUE TITLE
중고 물품을 조회한다.

### ISSUE THREAD

**Issue by sunghyun0610** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_BE#12]
## 📌 작업 내용

<br/>

## ✅ To-Do

- [ ] 구매자의 노출 범위에 있으면 조회된다.
- [ ] 사용자는 대표 썸네일 사진, 제목, 동네, 올린 시간, 최저 입찰가, 남은 마감 시간을 확인할 수 있다.
- [ ] 카테고리를 선택하여 물품을 조회할 수 있다.
- [ ] 검색을 통해 물품을 조회할 수 있다.
- [ ] 초기 검색은 일치 혹은 부분일치 검색만 용한다.
- [ ] 검색 기록을 사용자에게 보여준다. -> 유저도메인으로 변경
- [ ] 기본적으로 최신 순으로 정렬할 수 있다.
- [ ] 사용자의 위도 경도(중심좌표) ->여기서부터 100km

<br/>
