### ISSUE TITLE
사용자는 활동 지역을 선택할 수 있다.

### ISSUE THREAD

**Issue by Icecoff22** [prgrms-web-devcourse-final-project/WEB1_1_J1P5_BE#48]
## 📌 작업 내용
- 활동 지역 선택
<br/>

## ✅ To-Do

- [x] 법정동 데이터 db에 추가
- [x] 활동지역 동네 검색 기능 추가
- [x] 활동지역 동네 저장 기능 추가
- [ ] (고도화) db에 경량화 읍면동 테이블 두어 위치 기반 동네 검색 시 응답 속도 개선
<br/>
